# Generated by Django 4.2.29 on 2026-03-24 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'app_facility',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'app_organization',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_zone',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('unit_of_measure', models.CharField(default='EA', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_sku',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='app_masters.zone')),
            ],
            options={
                'db_table': 'app_location',
            },
        ),
        migrations.CreateModel(
            name='FacilityZone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.facility')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.zone')),
            ],
            options={
                'db_table': 'app_facility_zone',
            },
        ),
        migrations.CreateModel(
            name='FacilitySKU',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.facility')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.sku')),
            ],
            options={
                'db_table': 'app_facility_sku',
            },
        ),
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.facility')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_masters.location')),
            ],
            options={
                'db_table': 'app_facility_location',
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='locations',
            field=models.ManyToManyField(related_name='facilities', through='app_masters.FacilityLocation', to='app_masters.location'),
        ),
        migrations.AddField(
            model_name='facility',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='skus',
            field=models.ManyToManyField(related_name='facilities', through='app_masters.FacilitySKU', to='app_masters.sku'),
        ),
        migrations.AddField(
            model_name='facility',
            name='zones',
            field=models.ManyToManyField(related_name='facilities', through='app_masters.FacilityZone', to='app_masters.zone'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uq_zone_org_code'),
        ),
        migrations.AddConstraint(
            model_name='sku',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uq_sku_org_code'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uq_location_org_code'),
        ),
        migrations.AddConstraint(
            model_name='facilityzone',
            constraint=models.UniqueConstraint(fields=('facility', 'zone'), name='uq_facility_zone'),
        ),
        migrations.AddConstraint(
            model_name='facilitysku',
            constraint=models.UniqueConstraint(fields=('facility', 'sku'), name='uq_facility_sku'),
        ),
        migrations.AddConstraint(
            model_name='facilitylocation',
            constraint=models.UniqueConstraint(fields=('facility', 'location'), name='uq_facility_location'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('org', 'code'), name='uq_facility_org_code'),
        ),
    ]
