# Generated by Django 4.2.29 on 2026-03-24 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


PERMISSIONS = (
    ("org.read", "Organization read", "Read organization details for accessible orgs."),
    ("org.update", "Organization update", "Update organization details."),
    ("org.create", "Organization create", "Create organizations."),
    ("org.list_all", "Organization list all", "List all organizations across the platform."),
    ("users.manage.org", "Organization user management", "Manage user access grants inside an organization."),
    ("users.manage.platform", "Platform user management", "Manage pending users, statuses, and platform admins."),
    ("masters.read", "Masters read", "Read master data."),
    ("masters.manage", "Masters manage", "Create and update master data."),
    ("inventory.read", "Inventory read", "Read inventory balances and ledger data."),
    ("transactions.read", "Transactions read", "Read transactions."),
    ("transactions.manage", "Transactions manage", "Create, execute, and cancel transactions."),
    ("operations.execute", "Operations execute", "Run convenience warehouse operations."),
)

ROLES = (
    (
        "platform_admin",
        "Platform Admin",
        "PLATFORM",
        (
            "org.read",
            "org.update",
            "org.create",
            "org.list_all",
            "users.manage.org",
            "users.manage.platform",
            "masters.read",
            "masters.manage",
            "inventory.read",
            "transactions.read",
            "transactions.manage",
            "operations.execute",
        ),
    ),
    (
        "org_admin",
        "Organization Admin",
        "ORG",
        (
            "org.read",
            "org.update",
            "users.manage.org",
            "masters.read",
            "masters.manage",
            "inventory.read",
            "transactions.read",
            "transactions.manage",
            "operations.execute",
        ),
    ),
    (
        "facility_manager",
        "Facility Manager",
        "ORG",
        (
            "org.read",
            "masters.read",
            "inventory.read",
            "transactions.read",
            "transactions.manage",
            "operations.execute",
        ),
    ),
    (
        "operator",
        "Operator",
        "ORG",
        (
            "org.read",
            "masters.read",
            "inventory.read",
            "transactions.read",
            "operations.execute",
        ),
    ),
    (
        "viewer",
        "Viewer",
        "ORG",
        (
            "org.read",
            "masters.read",
            "inventory.read",
            "transactions.read",
        ),
    ),
)


def seed_roles_and_permissions(apps, schema_editor):
    Permission = apps.get_model("app_masters", "Permission")
    Role = apps.get_model("app_masters", "Role")
    RolePermission = apps.get_model("app_masters", "RolePermission")

    permission_by_code = {}
    for code, name, description in PERMISSIONS:
        permission, _ = Permission.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": description},
        )
        permission_by_code[code] = permission

    for code, name, scope, permission_codes in ROLES:
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={"name": name, "description": name, "scope": scope},
        )
        for permission_code in permission_codes:
            RolePermission.objects.get_or_create(
                role=role,
                permission=permission_by_code[permission_code],
            )


def unseed_roles_and_permissions(apps, schema_editor):
    Permission = apps.get_model("app_masters", "Permission")
    Role = apps.get_model("app_masters", "Role")

    Role.objects.filter(code__in=[code for code, *_rest in ROLES]).delete()
    Permission.objects.filter(code__in=[code for code, *_rest in PERMISSIONS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=32)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'app_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('PLATFORM', 'Platform'), ('ORG', 'Organization')], max_length=16)),
            ],
            options={
                'db_table': 'app_role',
            },
        ),
        migrations.CreateModel(
            name='UserPlatformRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_assignments', to='app_masters.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_role_assignments', to='app_masters.appuser')),
            ],
            options={
                'db_table': 'app_user_platform_role',
            },
        ),
        migrations.CreateModel(
            name='UserOrgMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=16)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='app_masters.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_role_memberships', to='app_masters.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to='app_masters.appuser')),
            ],
            options={
                'db_table': 'app_user_org_membership',
            },
        ),
        migrations.CreateModel(
            name='UserMembershipFacility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_assignments', to='app_masters.facility')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to='app_masters.userorgmembership')),
            ],
            options={
                'db_table': 'app_user_membership_facility',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='app_masters.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='app_masters.role')),
            ],
            options={
                'db_table': 'app_role_permission',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='app_masters.RolePermission', to='app_masters.permission'),
        ),
        migrations.AddConstraint(
            model_name='appuser',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='uq_app_user_email_non_empty'),
        ),
        migrations.AddConstraint(
            model_name='userplatformrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='uq_user_platform_role'),
        ),
        migrations.AddConstraint(
            model_name='userorgmembership',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='uq_user_org_membership'),
        ),
        migrations.AddConstraint(
            model_name='usermembershipfacility',
            constraint=models.UniqueConstraint(fields=('membership', 'facility'), name='uq_user_membership_facility'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uq_role_permission'),
        ),
        migrations.RunPython(seed_roles_and_permissions, unseed_roles_and_permissions),
    ]
