# Generated by Django 5.2.12 on 2026-03-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_masters", "0003_facility_warehouse_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="last_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_active_users",
                to="app_masters.facility",
            ),
        ),
    ]
