# Generated by Django 4.2.29 on 2026-03-24 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_operations', '0001_initial'),
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('entry_type', models.CharField(choices=[('PICK', 'Pick'), ('DROP', 'Drop')], max_length=10)),
                ('entity_type', models.CharField(choices=[('LOCATION', 'Location'), ('ZONE', 'Zone'), ('INVOICE', 'Invoice'), ('VIRTUAL_BUCKET', 'Virtual Bucket'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('entity_code', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=12)),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='app_operations.drop')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ledger_entries', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
                ('pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='app_operations.pick')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_ledger_entries', to='app_masters.sku')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='app_operations.transaction')),
            ],
            options={
                'db_table': 'app_inventory_ledger',
                'indexes': [models.Index(fields=['org', 'facility', 'sku', 'created_at'], name='idx_ledger_org_fac_sku_date'), models.Index(fields=['transaction'], name='idx_ledger_txn')],
            },
        ),
        migrations.CreateModel(
            name='InventoryBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('entity_type', models.CharField(choices=[('LOCATION', 'Location'), ('ZONE', 'Zone'), ('INVOICE', 'Invoice'), ('VIRTUAL_BUCKET', 'Virtual Bucket'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('entity_code', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('quantity_on_hand', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quantity_reserved', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_balances', to='app_masters.sku')),
            ],
            options={
                'db_table': 'app_inventory_balance',
                'indexes': [models.Index(fields=['org', 'facility', 'sku'], name='idx_inv_bal_org_fac_sku'), models.Index(fields=['org', 'facility', 'entity_type', 'entity_code'], name='idx_inv_bal_entity')],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorybalance',
            constraint=models.UniqueConstraint(fields=('org', 'facility', 'sku', 'entity_type', 'entity_code', 'batch_number'), name='uq_inv_balance'),
        ),
    ]
