/**
 * Reads .env and generates src/environments/environment.ts at dev startup.
 * Run automatically via the "prestart" npm script.
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const envFile = resolve(root, '.env');
const outFile = resolve(root, 'src/environments/environment.ts');

// Parse .env file
const env = {};
if (existsSync(envFile)) {
  readFileSync(envFile, 'utf8')
    .split('\n')
    .forEach(line => {
      const match = line.match(/^\s*([^#=\s][^=]*?)\s*=\s*(.*?)\s*$/);
      if (match) env[match[1]] = match[2].replace(/^['"]|['"]$/g, '');
    });
} else {
  console.warn('[generate-env] Warning: .env file not found — using empty defaults');
}

const get = (key, fallback = '') => env[key] ?? fallback;

const content = `// AUTO-GENERATED by scripts/generate-env.mjs — do not edit by hand.
// Source: .env  (gitignored — create from .env.example)
export const environment = {
  production: false,
  apiUrl: '${get('VITE_API_URL', 'http://localhost:8010/api/v1')}',
  firebase: {
    apiKey: '${get('VITE_FIREBASE_API_KEY')}',
    authDomain: '${get('VITE_FIREBASE_AUTH_DOMAIN')}',
    projectId: '${get('VITE_FIREBASE_PROJECT_ID')}',
  }
};
`;

writeFileSync(outFile, content, 'utf8');
console.log('[generate-env] src/environments/environment.ts written from .env');
