# Generated by Django 5.2.12 on 2026-03-28 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_masters", "0004_appuser_last_facility"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=500)),
                (
                    "device_type",
                    models.CharField(
                        choices=[("ANDROID", "Android"), ("IOS", "iOS")], max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="device_tokens",
                        to="app_masters.facility",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to="app_masters.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "app_device_token",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "token"), name="uq_device_token_user_token"
                    )
                ],
            },
        ),
    ]
