# Generated by Django 4.2.29 on 2026-03-24 13:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_type', models.CharField(choices=[('MOVE', 'Move'), ('ORDER_PICK', 'Order Pick'), ('GRN', 'Goods Received Note'), ('PUTAWAY', 'Putaway'), ('RETURN', 'Return'), ('CYCLE_COUNT', 'Cycle Count'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_COMPLETED', 'Partially Completed')], default='PENDING', max_length=25)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_transaction',
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('source_entity_type', models.CharField(choices=[('LOCATION', 'Location'), ('ZONE', 'Zone'), ('INVOICE', 'Invoice'), ('VIRTUAL_BUCKET', 'Virtual Bucket'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('source_entity_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='app_masters.sku')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='app_masters.location')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='app_operations.transaction')),
            ],
            options={
                'db_table': 'app_pick',
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('dest_entity_type', models.CharField(choices=[('LOCATION', 'Location'), ('ZONE', 'Zone'), ('INVOICE', 'Invoice'), ('VIRTUAL_BUCKET', 'Virtual Bucket'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=20)),
                ('dest_entity_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to='app_masters.location')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
                ('paired_pick', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_drop', to='app_operations.pick')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='app_masters.sku')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='app_operations.transaction')),
            ],
            options={
                'db_table': 'app_drop',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org', 'facility', 'transaction_type', 'status'], name='idx_txn_org_fac_type_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['org', 'reference_number'], name='idx_txn_org_ref'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['transaction'], name='idx_pick_txn'),
        ),
        migrations.AddIndex(
            model_name='drop',
            index=models.Index(fields=['transaction'], name='idx_drop_txn'),
        ),
    ]
