# Generated by Django 5.2.12 on 2026-03-28 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_masters", "0004_appuser_last_facility"),
        ("app_operations", "0002_transaction_document_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWorkerLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("tasks_completed", models.IntegerField(default=0)),
                ("points_earned", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "app_daily_worker_log",
            },
        ),
        migrations.CreateModel(
            name="WorkerStats",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("tasks_completed", models.IntegerField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_task_completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "app_worker_stats",
            },
        ),
        migrations.AddField(
            model_name="drop",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drop",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_drops",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddField(
            model_name="drop",
            name="lock_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drop",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drop",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_drops",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddField(
            model_name="drop",
            name="points_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="drop",
            name="task_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drop",
            name="task_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drop",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pick",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_picks",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="lock_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pick",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pick",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_picks",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddField(
            model_name="pick",
            name="points_awarded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pick",
            name="task_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pick",
            name="task_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pick",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ASSIGNED", "Assigned"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="drop",
            index=models.Index(
                fields=["org", "task_status"], name="idx_drop_org_task_status"
            ),
        ),
        migrations.AddIndex(
            model_name="pick",
            index=models.Index(
                fields=["org", "task_status"], name="idx_pick_org_task_status"
            ),
        ),
        migrations.AddField(
            model_name="dailyworkerlog",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_worker_logs",
                to="app_masters.organization",
            ),
        ),
        migrations.AddField(
            model_name="dailyworkerlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_logs",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddField(
            model_name="workerstats",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="app_masters.organization",
            ),
        ),
        migrations.AddField(
            model_name="workerstats",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_stats",
                to="app_masters.appuser",
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyworkerlog",
            constraint=models.UniqueConstraint(
                fields=("user", "org", "date"), name="uq_daily_log_user_org_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="workerstats",
            constraint=models.UniqueConstraint(
                fields=("user", "org"), name="uq_worker_stats_user_org"
            ),
        ),
    ]
