# Generated by Django 5.2.12 on 2026-03-29 18:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_masters', '0004_appuser_last_facility'),
        ('app_operations', '0003_dailyworkerlog_workerstats_drop_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='document_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('po_number', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_purchase_order',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app_operations.purchaseorder'),
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('so_number', models.CharField(max_length=100)),
                ('customer_code', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PICKING', 'Picking'), ('DISPATCHED', 'Dispatched'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_sale_order',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app_operations.saleorder'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('org', 'po_number'), name='uq_po_org_number'),
        ),
        migrations.AddConstraint(
            model_name='saleorder',
            constraint=models.UniqueConstraint(fields=('org', 'so_number'), name='uq_so_org_number'),
        ),
    ]
