# Generated by Django 5.2.12 on 2026-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_operations', '0004_transaction_document_path_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='performed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pick',
            name='performed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
