apiVersion: v1
kind: Service
metadata:
  name: rozana-wms-uat
  namespace: uat
  labels:
    app: rozana-wms
    environment: uat
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: rozana-wms
    environment: uat
