# Generated by Django 5.2.12 on 2026-04-01 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_masters', '0004_appuser_last_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('connector_type', models.CharField(choices=[('STOCKONE', 'StockOne'), ('SAP', 'SAP'), ('ORACLE', 'Oracle')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text='Connection credentials: base_url, client_id, client_secret, warehouse_key, etc.')),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('enabled_entities', models.JSONField(default=list, help_text='List of entity types to sync, e.g. ["SKU", "INVENTORY", "ORDER"]')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connector_configs', to='app_masters.facility')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_connector_config',
            },
        ),
        migrations.CreateModel(
            name='ExternalEntityMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('SKU', 'SKU'), ('INVENTORY', 'Inventory'), ('ORDER', 'Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=30)),
                ('external_id', models.CharField(max_length=255)),
                ('internal_id', models.UUIDField()),
                ('external_hash', models.CharField(blank=True, default='', max_length=64)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mappings', to='connectors.connectorconfig')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_entity_mappings', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_external_entity_mapping',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('SKU', 'SKU'), ('INVENTORY', 'Inventory'), ('ORDER', 'Order'), ('PURCHASE_ORDER', 'Purchase Order'), ('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('cursor_state', models.JSONField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='connectors.connectorconfig')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_sync_logs', to='app_masters.organization')),
            ],
            options={
                'db_table': 'app_sync_log',
            },
        ),
        migrations.AddConstraint(
            model_name='connectorconfig',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uq_connector_config_org_name'),
        ),
        migrations.AddIndex(
            model_name='externalentitymapping',
            index=models.Index(fields=['connector', 'entity_type'], name='idx_ext_mapping_connector_type'),
        ),
        migrations.AddConstraint(
            model_name='externalentitymapping',
            constraint=models.UniqueConstraint(fields=('connector', 'entity_type', 'external_id'), name='uq_ext_entity_mapping'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['connector', 'entity_type', 'created_at'], name='idx_sync_log_connector_entity'),
        ),
    ]
