# Generated by Django 5.2.12 on 2026-03-29 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_masters", "0004_appuser_last_facility"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New conversation", max_length=255)),
                (
                    "model_provider",
                    models.CharField(
                        default="ollama",
                        help_text="ollama, openai, or claude",
                        max_length=32,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        default="llama3.1",
                        help_text="Model identifier, e.g. llama3.1, gpt-4o, claude-sonnet-4-20250514",
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="app_masters.facility",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="app_masters.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="app_masters.appuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "components",
                    models.JSONField(
                        blank=True,
                        help_text="Structured UI components for the frontend to render",
                        null=True,
                    ),
                ),
                (
                    "tool_calls",
                    models.JSONField(
                        blank=True, help_text="LLM tool call requests", null=True
                    ),
                ),
                (
                    "tool_results",
                    models.JSONField(
                        blank=True, help_text="Tool execution results", null=True
                    ),
                ),
                ("token_count", models.IntegerField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app_ai.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="app_ai_conv_user_id_9e1e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["org", "user"], name="app_ai_conv_org_id_a20209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="app_ai_mess_convers_2f0240_idx",
            ),
        ),
    ]
