// AUTO-GENERATED by scripts/generate-env.mjs — do not edit by hand.
// Source: .env  (gitignored — create from .env.example)
export const environment = {
  production: false,
  apiUrl: 'http://localhost:8010/api/v1',
  firebase: {
    apiKey: 'AIzaSyDkNFp1Gowt2C4K9zf4eC9URhSgtx2rhQ4',
    authDomain: 'yesworks-d6789.firebaseapp.com',
    projectId: 'yesworks-d6789',
  }
};
