# Generated by Django 5.2.12 on 2026-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondocumentconfig',
            name='template_html',
            field=models.TextField(blank=True, default='', help_text='Raw HTML with Django template syntax. When set, overrides template_name and is rendered directly from the database. Available context: {{ transaction }}, {{ org }}, {{ facility }}, {{ generated_at }}.'),
        ),
    ]
