# Generated by Django 5.2.12 on 2026-04-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_documents', '0002_transactiondocumentconfig_template_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondocumentconfig',
            name='template_html',
        ),
    ]
