server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /web/ {
        try_files $uri $uri/ /web/index.html;
    }

    location = / {
        return 302 /web/;
    }
}
